site_name: 'jll-ds-documentation'
repo_url: https://github.com/backstage/backstage
edit_uri: blob/master/docs/

nav:
  - 'Docs': 'https://designsystem-dev.jll.com/?path=/story/1-welcome--page'
plugins:
  - techdocs-core
